# -*- coding: utf-8 -*-
"""DhaneshKumar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z6GrYPh5z8KRkQlj5llsY9cpQxxWeZVp
"""

#Copy this text below. See if you can do it with just the one print statement!

str="I am signing up for Replit's 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happend to be. No excuses for not coding from the middle of a field!"
print(str)

#	ii) Crete a dictionary for malware and description. And perform all the dictionary functions.

dict={"Ransomware":"disables victim's access to data until ransom is paid","Fileless Malware":"makes changes to files that are native to the OS","Spyware":"collects user activity data without their knowledge"}
print(dict)
print(len(dict))
print(type(dict))

#2) A person bought a mobile for the cost of 12,300 with additionally he pays 18% of GST. Calculate Net Price and GST amount of the mobile. 

com=12300         #com=cost of mobile
gstp=18           #gstp=gst in perscerntage

gst=(com/100)*18  
np=com+gst        #np=netprice

print("GST", gst)
print("NetPrice", np)

#3) Create a dataset for cybercrime, respective to IPC Section, offence and penalties. 

import pandas as pd
df=pd.DataFrame({})

import pandas as pd

df=pd.DataFrame({
"Offence":["sending Threatning messege by email","Sending defamatory messege by email","Forgery of electronic Records","Bogus Website & Cyber Frauds","Email Spoofing","WebJacking","Email-Abuse","Online Sale of Drugs","Online Sale of Arms"],
"Laws":["Sec.503 IPC","SEC.499 IPC","SEC.463 IPC","SEC.420 IPC","SEC.463 IPC","SEC.383 IPC","SEC.500 IPC","NDPS ACT 1985","ARMS ATTACK1959"], 
})

#df["crime_type"]=df['media'].apply(lambda x: 'socialmedia' if x=="social" else 'others')
#"media":["social","social","no social","no social","social","social","social","no social","no social","no social"],
print(df)
	#i) Retrieve the crime that happens because of social media apps like twitter / WhatsApp/ Facebook.

#4) Get 10 students data with respective name, age, dob, weight and height.  
#i) Find the BMI (Body Mass Index) and health status.Health status as categorial data. (Underweight, overweight, healthy)  

import pandas as pd
df=pd.DataFrame({})

import pandas as pd

df=pd.DataFrame({
"name":["arjun","akash","dhinesh","bharath","gokul","ramesh","suresh","xavier","ashwin","guru"],
"dob":[2001,2001,2000,2002,2001,2000,1994,1984,1997,2004],
"weight":[56,76,86,45,65,76,34,65,76,45],
"height":[178,198,178,198,178,178,189,167,167,155]


})
df['age']=2022-df['dob']



print(df)

#5) Calculate the Electricity Bill for household and Commercial according to the given condition. For Household: 0 to 100 Units = Rs 0.50/unit, 101 to 200 Units = Rs 0.75/unit, 201 to 300 Units = Rs 1.20/unit, above 300 Units = Rs 1.50/unit. Write a python code to calculate EB Bill using nested. If condition.


unit=int(input("Number of Units Consumed:"))
if(0<=unit<=100):
  eb=(unit*0.50)
  print("Electricity Bill",eb)
if(101<=unit<=200):
  eb=(unit*0.75)
  print("Electricity Bill=",eb)
if(201<=unit<=300):
  eb=(unit*1.20)
  print("Electricity Bill=",eb)
if(301<=unit):
  eb=(unit*1.50)
  print("Electricity Bill=",eb)